//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

//MARK: Presenter - Router
protocol ___VARIABLE_productName:identifier___PresenterToRouterProcotol: class {
    static func createModule() -> UIViewController
}

//MARK: View - Presenter
protocol ___VARIABLE_productName:identifier___ViewToPresenterProtocol: class {
    var view: ___VARIABLE_productName:identifier___PresenterToViewProtocol? {get set}
    var interactor: ___VARIABLE_productName:identifier___PresenterToInteractorProtocol? {get set}
    var router: ___VARIABLE_productName:identifier___PresenterToRouterProcotol? {get set}
    
    func updateView()
}

//MARK: Presenter - View
protocol ___VARIABLE_productName:identifier___PresenterToViewProtocol {
    func showData()
    func showError(errorName: String, statusCode: Int)
    func hideHud()
}

//MARK: Presenter - Interactor
protocol ___VARIABLE_productName:identifier___PresenterToInteractorProtocol {
    var presenter: ___VARIABLE_productName:identifier___InteractorToPresenterProtocol? {get set}
    func fetchData()
}

//MARK: Interactor - Presenter
protocol ___VARIABLE_productName:identifier___InteractorToPresenterProtocol: class {
    func dataFetched()
    func dataFetchedFailed(errorName: String ,statusCode: Int)
    func viewLoading()
}

