//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit

class ___VARIABLE_productName:identifier___PresenterToRouter: BaseClass, ___VARIABLE_productName:identifier___PresenterToRouterProcotol {
    
    static func createModule() -> UIViewController {
        let view = mainStoryBoard.instantiateViewController(withIdentifier: "___VARIABLE_productName:identifier___ViewController") as! ___VARIABLE_productName:identifier___ViewController
        var interactor: ___VARIABLE_productName:identifier___PresenterToInteractorProtocol = ___VARIABLE_productName:identifier___PresenterToInteractor()
        let presenter: ___VARIABLE_productName:identifier___ViewToPresenterProtocol & ___VARIABLE_productName:identifier___InteractorToPresenterProtocol = ___VARIABLE_productName:identifier___ViewToPresenter()
        let router: ___VARIABLE_productName:identifier___PresenterToRouterProcotol = ___VARIABLE_productName:identifier___PresenterToRouter()
        
        presenter.view = view
        presenter.router = router
        presenter.interactor = interactor
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
}
