//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import Foundation
import UIKit

class ___VARIABLE_productName:identifier___ViewToPresenter: ___VARIABLE_productName:identifier___ViewToPresenterProtocol {

    var view: ___VARIABLE_productName:identifier___PresenterToViewProtocol?
    var interactor: ___VARIABLE_productName:identifier___PresenterToInteractorProtocol?
    var router: ___VARIABLE_productName:identifier___PresenterToRouterProcotol?
    
    func updateView() {
        interactor?.fetchData()
    }

}

extension ___VARIABLE_productName:identifier___ViewToPresenter: ___VARIABLE_productName:identifier___InteractorToPresenterProtocol{
    func dataFetched() {
        view?.showData()
    }
    
    func dataFetchedFailed(errorName: String ,statusCode: Int) {
        view?.showError(errorName: errorName, statusCode: statusCode)
    }
    
    func viewLoading() {
        view?.hideHud()
    }
}
