//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Yana Mulyana
//

import UIKit
import Alamofire

class ___VARIABLE_productName:identifier___PresenterToInteractor: ___VARIABLE_productName:identifier___PresenterToInteractorProtocol {

    var presenter: ___VARIABLE_productName:identifier___InteractorToPresenterProtocol?
    func fetchData() {
            //do something with alamofire
    }
}
